### ISSUE TITLE
Entity does not spawn immediately after startup

### ISSUE THREAD

**Issue by m4kvn** [m4kvn/spigot-homes#1]

**Comment by hashibiroko** [comment]
Maybe it's because it's not registered as a custom entity.

**Comment by m4kvn** [comment]
Created a registration process for CustomEntityArmorStand.

```kotlin
private fun addCustomEntityType(
    minecraftKey: MinecraftKey,
    entityType: EntityType,
) {
    val dataFixer = DataConverterRegistry.a()
    val worldVersion = SharedConstants.b().b().c()
    val schema = dataFixer.getSchema(DataFixUtils.makeKey(worldVersion))
    val choiceType = schema.findChoiceType(DataConverterTypes.q) as TaggedChoice.TaggedChoiceType<Any>
    val typeMap = choiceType.types()
    typeMap["$minecraftKey"] = typeMap["${entityType.key}"]
}

fun registerHomeDisplayEntity() {
    val customName = "homes_display"
    val minecraftKey = MinecraftKey.a(customName) ?: return
    addCustomEntityType(minecraftKey, EntityType.ARMOR_STAND)
    
    val entityTypesCreation = { _: EntityTypes<Entity>, world: World ->
        CustomEntityArmorStand(world)
    }
    val entityTypes = EntityTypes.Builder
        .a<EntityArmorStand>(entityTypesCreation, EnumCreatureType.h)
        .a(0.5f, 1.975f)
        .a(10)
        .a(customName)
    IRegistry.a(IRegistry.X, customName, entityTypes)
}
```

Ran it and it didn't work, so trying to figure out why.

```
java.lang.IllegalStateException: Registry is already frozen
        at net.minecraft.core.RegistryMaterials.e(SourceFile:365) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.world.entity.EntityTypes.<init>(EntityTypes.java:309) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.world.entity.EntityTypes$Builder.a(EntityTypes.java:668) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
```

**Comment by hashibiroko** [comment]
Think `IRegistry.X` in `IRegistry.a(IRegistry.X, customName, entityTypes)` might be wrong.

**Comment by m4kvn** [comment]
It's an error in `new EntityTypes(...)` of `EntityTypes.Builder::a(customName)`, so that might not be it.

**Comment by m4kvn** [comment]
Shouldn't you have done `IRegistry.a(IRegistry.X, customName, entityTypes)` in the first place?

**Comment by m4kvn** [comment]
When DisplayEntity is displayed, it is now re-generated instead of using the existing one.
